# fly.toml app configuration file generated for routeflare-main on 2026-06-22T12:43:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'routeflare-main'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  NODE_ENV = 'production'
  DATA_DIR = '/data'

[mounts]
  source = 'routeflare_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
